sudo: false
language: python
os:
- linux
- osx
branches:
    except:
    - gh-pages
matrix:
    include:
    - python: "2.6"
      env: TOXENV=py26
    - python: "2.7"
      env: TOXENV=py27
    - python: "3.1"
      env: TOXENV=py31
    - python: "3.2"
      env: TOXENV=py32
    - python: "3.3"
      env: TOXENV=py33
    - python: "3.4"
      env: TOXENV=py34
    - python: "pypy"
      env: TOXENV=pypy
    allow_failures:
    - env: TOXENV=pypy
install:
- if [[ ! -z $TOXENV ]]; then pip install tox; fi 
script:
- if [[ ! -z $TOXENV ]]; then tox -e $TOXENV; fi
notifications:
    email: false
